config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # URL root should lead to university list
  root 'universities#index'

  get 'requests/new', to: 'add_requests#new'
  post 'requests/new', to: 'add_requests#create'
  patch 'requests/:id', to: 'add_requests#close'

  get 'sessions/new'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post '/comments/create', to: 'comments#create'
  patch '/comments/:id', to: 'comments#report'
  resources :comments, only: %i[create destroy]

  get '/dashboard/moderator', to: 'static_pages#moderator'
  get '/dashboard/administrator', to: 'static_pages#administrator'
  get '/compare', to: 'static_pages#compare'
  delete '/compare', to: 'static_pages#remove_compare'
  get '/help', to: 'static_pages#help'

  # Only allow index/show actions on universities
  resources :universities, only: %i[index show toggle_favorite], path: '/' do
    get '/edit', to: 'universities#edit'
    patch '/update', to: 'universities#update'
    patch '/', to: 'universities#toggle_favorite'
  end
end

app/models/add_request.rb
# frozen_string_literal: true

class AddRequest < ApplicationRecord
  belongs_to :user
  belongs_to :university
end

app/controllers/add_requests_controller.rb
# frozen_string_literal: true

class AddRequestsController < ApplicationController
  # Loads the add request creation page, and redirects back if no ID was provided
  def new
    redirect_to(request.referer || root_url) if params[:university_id].blank?
    @request = AddRequest.new
    @university = University.find(params[:university_id])
  end

  # Creates the new add request using information provided by the user on the request page
  def create
    @request = AddRequest.new(params.require(:add_request).permit(:university_id, :content))
    @university = University.find(params[:add_request][:university_id])
    @request.user_id = current_user.id
    @request.status = false
    if @request.save
      flash[:success] = 'Request submitted!'
      redirect_to @university
    else
      render 'new'
    end
  end

  # Sets the status of a request so it no longer shows up in the dashboard
  def close
    @request = AddRequest.find(params[:id])
    @request.status = true
    flash[:success] = 'Request closed!' if @request.save

    redirect_to request.referer || root_url
  end
end

app/helpers/add_requests_helper.rb
# frozen_string_literal: true

module AddRequestsHelper
end

app/views/add_requests/new.html.erb
<!-- This page handles new information requests for universities -->
<h2 class="top-text">Information Request</h2>
<% if current_user.errors.any? %>
  <div class="alert alert-danger">
    <p class="h6"><%= pluralize(current_user.errors.count, "Error") + ":" %></p>
    <ul>
      <% current_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_for @request, url: requests_new_path do |f| %>
  <%= f.hidden_field :university_id, value: @university.id %>
  <div class="form-group">
    <label for="input-university">University</label>
    <%= text_field_tag nil, @university.name, disabled: true, class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="input-content">Request Information</label>
    <%= f.text_area :content, class: "form-control", placeholder: "Request details..." %>
  </div>
  <%= f.submit "Submit Request", class: "btn btn-primary" %>
<% end %>