config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # URL root should lead to university list
  root 'universities#index'

  get 'requests/new', to: 'add_requests#new'
  post 'requests/new', to: 'add_requests#create'
  patch 'requests/:id', to: 'add_requests#close'

  get 'sessions/new'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post '/comments/create', to: 'comments#create'
  patch '/comments/:id', to: 'comments#report'
  resources :comments, only: %i[create destroy]

  get '/dashboard/moderator', to: 'static_pages#moderator'
  get '/dashboard/administrator', to: 'static_pages#administrator'
  get '/compare', to: 'static_pages#compare'
  delete '/compare', to: 'static_pages#remove_compare'
  get '/help', to: 'static_pages#help'

  # Only allow index/show actions on universities
  resources :universities, only: %i[index show toggle_favorite], path: '/' do
    get '/edit', to: 'universities#edit'
    patch '/update', to: 'universities#update'
    patch '/', to: 'universities#toggle_favorite'
  end
end

app/models/university.rb
# frozen_string_literal: true

# rubocop:disable Metrics/ClassLength
class University < ApplicationRecord
  has_many :comments, dependent: :destroy

  # An array of states used for dropdown menus
  # rubocop:disable Style/ClassVars
  @@states = [
    'Alabama',
    'Alaska',
    'America Samoa',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'District of Columbia',
    'Federated States Of Micronesia',
    'Florida',
    'Georgia',
    'Guam',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Marshall Islands',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Palau',
    'Pennsylvania',
    'Puerto Rico',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virgin Island',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming'
  ]
  # rubocop:enable Style/ClassVars
  cattr_reader :states

  # Filter university list by name if a search term is given
  def self.search(search)
    if search.blank?
      all
    else
      where(['lower(name) like ?', "%#{search.downcase}%"]).all
    end
  end

  # rubocop:disable Metrics/MethodLength, Metrics/AbcSize
  # rubocop:disable Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity
  # rubocop:disable Metrics/ParameterLists
  def self.adv_search(name, city, state, zip, size_min, size_max,
                      acceptance_rate_min, acceptance_rate_max, sat_reading_min,
                      sat_reading_max, sat_math_min, sat_math_max, act_min, act_max,
                      cost_in_min, cost_in_max, cost_out_min, cost_out_max)
    query = ''
    params = []

    if name.present?
      query += "#{'AND ' if query.present?}lower(name) like ? "
      params << "%#{name.downcase}%"
    end

    if city.present?
      query += "#{'AND ' if query.present?}lower(city) like ? "
      params << "%#{city.downcase}%"
    end

    if state.present?
      query += "#{'AND ' if query.present?}lower(state) like ? "
      params << "%#{state.downcase}%"
    end

    if zip.present?
      query += "#{'AND ' if query.present?}lower(zip_code) like ? "
      params << "%#{zip.downcase}%"
    end

    if size_min.present?
      query += "#{'AND ' if query.present?}student_count >= ? "
      params << size_min
    end

    if size_max.present?
      query += "#{'AND ' if query.present?}student_count <= ? "
      params << size_max
    end

    if acceptance_rate_min.present?
      query += "#{'AND ' if query.present?}acceptance_rate >= ? "
      params << acceptance_rate_min
    end

    if acceptance_rate_max.present?
      query += "#{'AND ' if query.present?}acceptance_rate <= ? "
      params << acceptance_rate_max
    end

    if sat_reading_min.present?
      query += "#{'AND ' if query.present?}q3_sat_reading > ? "
      params << sat_reading_min
    end

    if sat_reading_max.present?
      query += "#{'AND ' if query.present?}q1_sat_reading < ? "
      params << sat_reading_max
    end

    if sat_math_min.present?
      query += "#{'AND ' if query.present?}q3_sat_math > ? "
      params << sat_math_min
    end

    if sat_math_max.present?
      query += "#{'AND ' if query.present?}q1_sat_math < ? "
      params << sat_math_max
    end

    if act_min.present?
      query += "#{'AND ' if query.present?}q3_act > ? "
      params << act_min
    end

    if act_max.present?
      query += "#{'AND ' if query.present?}q1_act < ? "
      params << act_max
    end

    if cost_in_min.present?
      query += "#{'AND ' if query.present?}cost_in >= ? "
      params << cost_in_min
    end

    if cost_in_max.present?
      query += "#{'AND ' if query.present?}cost_in <= ? "
      params << cost_in_max
    end

    if cost_out_min.present?
      query += "#{'AND ' if query.present?}cost_out >= ? "
      params << cost_out_min
    end

    if cost_out_max.present?
      query += "#{'AND ' if query.present?}cost_out <= ? "
      params << cost_out_max
    end

    if query.empty?
      all
    else
      where([query, params].flatten).all
    end
  end
  # rubocop:enable Metrics/MethodLength, Metrics/AbcSize
  # rubocop:enable Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity
  # rubocop:enable Metrics/ParameterLists

  # Determines if this university has SAT reading score information
  def sat_reading?
    !(q1_sat_reading.nil? || q3_sat_reading.nil?)
  end

  # Determines if this university has SAT math score information
  def sat_math?
    !(q1_sat_math.nil? || q3_sat_math.nil?)
  end

  # Determines if this university has ACT score information
  def act?
    !(q1_act.nil? || q3_act.nil?)
  end

  # Retrieves the school's URL prefixed with 'http://'
  def full_url
    if school_site.start_with? 'http://'
      school_site
    else
      "http://#{school_site}"
    end
  end
end
# rubocop:enable Metrics/ClassLength

app/controllers/universities_controller.rb
# frozen_string_literal: true

class UniversitiesController < ApplicationController
  # Show a list of universities, filtered by name if the parameter 'q' is
  # passed to the controller
  # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
  def index
    @universities = []
    if params['mode'] == 'adv'
      name = params['name']
      city = params['city']
      state = params['state']
      zip = params['zip']
      size_min = params['size_min']
      size_max = params['size_max']
      acceptance_rate_min = params['acceptance_rate_min']
      acceptance_rate_max = params['acceptance_rate_max']
      sat_reading_min = params['sat_reading_min']
      sat_reading_max = params['sat_reading_max']
      sat_math_min = params['sat_math_min']
      sat_math_max = params['sat_math_max']
      act_min = params['act_min']
      act_max = params['act_max']
      cost_in_min = params['cost_in_min']
      cost_in_max = params['cost_in_max']
      cost_out_min = params['cost_out_min']
      cost_out_max = params['cost_out_max']
      @universities = University.adv_search(name, city, state, zip, size_min, size_max,
                                            acceptance_rate_min, acceptance_rate_max, sat_reading_min,
                                            sat_reading_max, sat_math_min, sat_math_max, act_min, act_max,
                                            cost_in_min, cost_in_max, cost_out_min, cost_out_max)
    else
      @universities = University.search(params['q'])
    end

    @result_size = @universities.size
    @universities = @universities.paginate(page: params['page'], per_page: 20).order('name ASC')
  end
  # rubocop:enable Metrics/AbcSize, Metrics/MethodLength

  # Shows a specific university's information
  def show
    @university = University.find(params[:id])
  end

  # Displays the edit page for the university
  def edit
    @university = University.find(params[:university_id])
  end

  # Updates the information in the database based on the information
  # entered in the edit page
  def update
    @university = University.find(params[:university_id])
    if @university.update(university_params)
      flash[:success] = 'Information updated!'
      redirect_to @university
    else
      render 'edit'
    end
  end

  # Toggles the favorite status of this university for the current user
  # rubocop:disable Metrics/AbcSize
  def toggle_favorite
    return if current_user.nil?

    if current_user.favorite?(params[:university_id])
      current_user.remove_favorite(params[:university_id])
    else
      current_user.add_favorite(params[:university_id])
    end

    flash[:success] = 'Favorites list updated!'
    redirect_to request.referer || root_url
  end
  # rubocop:enable Metrics/AbcSize

  private

  # Checks to make sure only valid parameters are accepted
  def university_params
    params.require(:university).permit(:name, :city, :state, :zip_code, \
                                       :student_count, :q1_sat_reading, :q3_sat_reading, :q1_sat_math, \
                                       :q3_sat_math, :q1_act, :q3_act, :acceptance_rate, :cost_in, :cost_out)
  end
end

app/helpers/universities_helper.rb
# frozen_string_literal: true

module UniversitiesHelper
end

app/views/universities/edit.html.erb
<!-- This page allows administrators to edit university information -->

<div class="container">
  <h2>University Information</h2>
  <% if @university.errors.any? %>
    <div class="alert alert-danger">
      <p class="h6"><%= pluralize(@university.errors.count, "Error") + ":" %></p>
      <ul>
        <% @university.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_for @university, url: university_update_path(@university) do |f| %>
    <div class="form-group">
      <%= f.label :name, "Name" %>
      <%= f.text_field :name, value: @university.name, class: "form-control" %>
    </div>
    <div class="form-row">
      <div class="col-sm-5 form-group">
        <%= f.label :city, "City" %>
        <%= f.text_field :city, value: @university.city, id: "cityInput", class: "form-control" %>
      </div>
      <div class="col-sm-3 form-group">
        <%= f.label :state, "State" %>
        <%= f.select :state, options_for_select(University.states, @university.state), {}, {class: "form-control"} %>
      </div>
      <div class="col-sm-4 form-group">
        <%= f.label :zip_code, "ZIP Code" %>
        <%= f.number_field :zip_code, value: @university.zip_code, min: 0, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :student_count, "Student Count" %>
      <%= f.number_field :student_count, value: @university.student_count, min: 0, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :acceptance_rate, "Acceptance Rate" %>
      <%= f.number_field :acceptance_rate, value: @university.acceptance_rate, min: 0, max: 100, class: "form-control" %>
    </div>
    <div class="form-group">
      <label>SAT Reading Scores</label>
      <div class="form-row">
        <div class="col-sm">
          <%= f.number_field :q1_sat_reading, value: @university.q1_sat_reading, min: 0, max: 800, class: "form-control" %>
        </div>
        <div class="col-sm-1 text-center my-auto">
          <span>to</span>
        </div>
        <div class="col-sm input">
          <%= f.number_field :q3_sat_reading, value: @university.q3_sat_reading, min: 0, max: 800, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <label>SAT Math Scores</label>
      <div class="form-row">
        <div class="col-sm">
          <%= f.number_field :q1_sat_math, value: @university.q1_sat_math, min: 0, max: 800, class: "form-control" %>
        </div>
        <div class="col-sm-1 text-center my-auto">
          <span>to</span>
        </div>
        <div class="col-sm input">
          <%= f.number_field :q3_sat_math, value: @university.q3_sat_math, min: 0, max: 800, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <label>ACT Composite Scores</label>
      <div class="form-row">
        <div class="col-sm">
          <%= f.number_field :q1_act, value: @university.q1_act, min: 0, max: 36, class: "form-control" %>
        </div>
        <div class="col-sm-1 text-center my-auto">
          <span>to</span>
        </div>
        <div class="col-sm input">
          <%= f.number_field :q3_act, value: @university.q3_act, min: 0, max: 36, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :cost_in, "In-State Cost" %>
      <%= f.number_field :cost_in, value: @university.cost_in, min: 0, step: 0.01, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :cost_out, "Out-Of-State Cost" %>
      <%= f.number_field :cost_out, value: @university.cost_out, min: 0, step: 0.01, class: "form-control" %>
    </div>

    <%= f.submit "Update", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/universities/index.html.erb
<!-- This page displays a list of all universities (paginated) and serves as University Guru's homepage -->

<script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
</script>

<% if params['mode'] == 'adv' || params['q'].present? %>
  <p>Search: <%= params['q'] %></p>	  <p class="small font-weight-bold mb-1">Search Criteria:</p>
<% end %>
<% if params['mode'] == 'adv' %>
  <% if params['name'].present? %>
    <span class="badge badge-light">Name: <%= params['name'].strip %></span>
  <% end %>
  <% if params['city'].present? %>
    <span class="badge badge-light">City: <%= params['city'].strip %></span>
  <% end %>
  <% if params['state'].present? %>
    <span class="badge badge-light">State: <%= params['state'].strip %></span>
  <% end %>
  <% if params['zip'].present? %>
    <span class="badge badge-light">ZIP Code: <%= params['zip'].strip %></span>
  <% end %>
  <% if params['size_min'].present? %>
    <span class="badge badge-light">School Size > <%= number_with_precision(params['size_min'].strip.to_i, precision: 0, delimiter: ',') %></span>
  <% end %>
  <% if params['size_max'].present? %>
    <span class="badge badge-light">School Size < <%= number_with_precision(params['size_max'].strip.to_i, precision: 0, delimiter: ',') %></span>
  <% end %>
  <% if params['acceptance_rate_min'].present? %>
    <span class="badge badge-light">Acceptance Rate > <%= params['acceptance_rate_min'].strip %>%</span>
  <% end %>
  <% if params['acceptance_rate_max'].present? %>
    <span class="badge badge-light">Acceptance Rate < <%= params['acceptance_rate_max'].strip %>%</span>
  <% end %>
  <% if params['sat_reading_min'].present? %>
    <span class="badge badge-light">SAT Reading Score > <%= params['sat_reading_min'].strip %></span>
  <% end %>
  <% if params['sat_reading_max'].present? %>
    <span class="badge badge-light">SAT Reading Score < <%= params['sat_reading_max'].strip %></span>
  <% end %>
  <% if params['sat_math_min'].present? %>
    <span class="badge badge-light">SAT Math Score > <%= params['sat_math_min'].strip %></span>
  <% end %>
  <% if params['sat_math_max'].present? %>
    <span class="badge badge-light">SAT Math Score < <%= params['sat_math_max'].strip %></span>
  <% end %>
  <% if params['act_min'].present? %>
    <span class="badge badge-light">ACT Score > <%= params['act_min'].strip %></span>
  <% end %>
  <% if params['act_max'].present? %>
    <span class="badge badge-light">ACT Score < <%= params['act_max'].strip %></span>
  <% end %>
  <% if params['cost_in_min'].present? %>
    <span class="badge badge-light">In-State Costs > $<%= number_with_precision(params['cost_in_min'].strip.to_f, precision: 2, delimiter: ',') %></span>
  <% end %>
  <% if params['cost_in_max'].present? %>
    <span class="badge badge-light">In-State Costs < $<%= number_with_precision(params['cost_in_max'].strip.to_f, precision: 2, delimiter: ',') %></span>
  <% end %>
  <% if params['cost_out_min'].present? %>
    <span class="badge badge-light">Out-of-State Costs > $<%= number_with_precision(params['cost_out_min'].strip.to_f, precision: 2, delimiter: ',') %></span>
  <% end %>
  <% if params['cost_out_max'].present? %>
    <span class="badge badge-light">Out-of-State Costs < $<%= number_with_precision(params['cost_out_max'].strip.to_f, precision: 2, delimiter: ',') %></span>
  <% end %>
<% elsif params['q'].present? %>
  <span class="badge badge-light">Query: <%= params['q'].strip %></span>
<% end %>
<% if params['mode'] == 'adv' || params['q'].present? %>
  <h6 class="mt-3"><%= "#{@result_size} #{'Result'.pluralize(@result_size)}" %></h6>
  <hr>
<% end %>

﻿<% unless @universities.empty? %>
	<%= will_paginate @universities, page_links: false, previous_label: "Previous", next_label: "Next", list_classes: %w(pagination justify-content-center d-flex d-md-none) %>
	<%= will_paginate @universities, list_classes: %w(pagination justify-content-center d-none d-sm-none d-md-flex) %>

    <% @universities.each do |university| %>
    <div class="container-fluid mb-3">
	<!--card body left-->
        <div class="row no-gutters">
            <div class="col-md-11 card border-primary">
                <div class="card-body">
                    <%= link_to university_path(university) do %>
                    <h3 class="card-title"><%= university.name %></h3>
                    <% end %>
                    <span class="text-muted"><%= university.city %>, <%= university.state %> <%= university.zip_code %></span>
                </div>
				<!--card footer-->
                <div class="card-footer border-primary text-muted">
                    <div class="row no-gutters">
                        <div class="col-sm-4">
                            <span class="h6">Student Count:</span>
                            <span>
                                <% if university.student_count.nil? %>
                                  Not Reported
                                <% else %>
                                  <%= number_with_precision(university.student_count, precision: 0, delimiter: ",") %>
                                <% end %>
                            </span>
                        </div>
                        <div class="col-sm-6">
                            <span class="h6">Tuition and Fees:</span>
                            <span>
                                <% if university.cost_in.nil? %>
                                  Not Reported
                                <% else %>
                                  $<%= number_with_precision(university.cost_in, precision: 2, delimiter: ",") %>
                                <% end %>
                            </span>
                        </div>
                        <div class="col-sm-2">
                            <%= link_to university_path(university) do %>
								                    <span class="text-primary stretched-link float-right">More Info</span>
                            <% end %>
                        </div>
                    </div>

                </div>
            </div>
			<!--card body right-->
            <div class="col-md-1">
                <div class="btn-group-vertical h-100 w-100">
                    <% if logged_in? %>
                      <% is_fav = current_user.favorite?(university.id.to_s) %>
                      <%= link_to university, action: :toggle_favorite, method: "patch", role: "button", class: "btn #{is_fav ? "btn-primary" : "btn-outline-primary"} d-flex flex-column", "data-toggle": "tooltip", "data-placement": "top", title: "#{is_fav ? "Remove from" : "Add to"} Favorites List" do %>
                          <%= image_tag("heart.png", width: "16px", height: "16px", class: "m-auto") %>
                      <% end %>
                    <% else %>
                      <%= link_to('#', role: "button", class: "btn btn-outline-primary d-flex flex-column disabled") do %>
                          <%= image_tag("heart.png", width: "16px", height: "16px", class: "m-auto") %>
                      <% end %>
                    <% end %>
                    <%= link_to({controller: :static_pages, action: :compare, university: university.id}, role: "button", class: "btn btn-outline-primary d-flex flex-column", "data-toggle": "tooltip", "data-placement": "bottom", title: "Add to Comparison") do %>
                        <%= image_tag("tick.png", width: "16px", height: "16px", class: "m-auto") %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
    <% end %>

	<%= will_paginate @universities, page_links: false, previous_label: "Previous", next_label: "Next", list_classes: %w(pagination justify-content-center d-flex d-md-none) %>
	<%= will_paginate @universities, list_classes: %w(pagination justify-content-center d-none d-sm-none d-md-flex) %>
<% end %>